Update to display last establishment card in full
kevinddchen/machikoro pull request #9
Opened 2022-04-03 21:11 UTC by AquaDragon

- Updated `PlayerInfo.js`

The last establishment card in each player's stack is now displayed in full.

2022-04-03 23:07 UTC, kevinddchen requested changes
Some minor suggestions

2022-04-03 23:07 UTC, kevinddchen commented on src/game/PlayerInfo.js
> +        if (est == last_est_id && count == est_p[est]-1) {
Should use `===` here for equality. Javascript is stupid.

2022-04-03 23:07 UTC, kevinddchen commented on src/game/PlayerInfo.js
> +          minis.push(
Maybe cleaner to use the if-else to determine whether to use `mini_path` or `img_path` and save this to a variable, since the call is the same otherwise.

2022-04-04 01:08 UTC, AquaDragon commented
Implemented code suggestions

2022-04-04 01:53 UTC, kevinddchen approved these changes
LGTM!

2022-04-04 01:53 UTC, merged