Add chat box
kevinddchen/machikoro pull request #97
Opened 2023-04-26 04:49 UTC by kevinddchen

Add a chat box where the log is. Buttons toggle between the log and chat.

Note that the chat is ephemeral, meaning that when the browser is refreshed they disappear. This is correct behavior of the `boardgame.io` framework.

This addresses #88 .

2023-04-26 12:20 UTC, AquaDragon requested changes
I improved the UI for the chatlog but there are still some issues:
- The linter keeps failing due to some null-assertion error and I'm not familiar with styling textscript, so that has to be fixed.
- When the game loads for the first time, the "Game Log" is not selected by default. (Trying to do the typescript equivalent of having '< input checked="checked" '> for the default button)
- I commented out some unused code when making changes to the UI. Do we usually remove them to make the code cleaner?

2023-04-26 19:06 UTC, AquaDragon commented
I just thought of a continuation we could do with the game log/chat buttons in which the tab that is not open could flash or change color if there is an update while it is not shown (i.e. if you're in the Game Log and there is a new Chat message, the tab will turn red or something)

2023-04-27 05:35 UTC, kevinddchen commented
‼️ Damn! looks good!

- Yeah, linter can be annoying, but hopefully it ensures better code-correctness. If anything, if types are wrong but code works, I don't mind helping with getting the types correct.
- Noted, I'll see what I can do. I also like the "hit enter to submit" so ill try to add that back in too.
- Sure, but deleting code is fine too. I am not offended.

2023-04-27 05:57 UTC, kevinddchen commented on src/board/TextPanel/TextPanel.tsx
> +  }
This is how the radio button for log is set by default.

First, we define some references to the HTML objects. This is the `logRadioRef` and `chatRadioRef` above. Then when the webpage loads, this `componentDidMount` function is run right after the `TextPanel` is loaded. This is just how React works. But this only runs once, so we can set the initial "checked" value without fixing it to some constant value.

2023-04-27 06:08 UTC, kevinddchen commented on src/board/TextPanel/Chat.tsx
> +  private entryBoxRef: React.RefObject<HTMLInputElement>;
The only thing I had to change to get the "enter" to send message was to change the type from `HTMLTextAreaElement` to `HTMLInputElement`, since you use an `input` instead of a `textarea`

2023-04-27 06:10 UTC, kevinddchen commented on src/styles/main.css
> +/*  overflow: scroll;*/
:+1: fair enough

2023-04-27 06:12 UTC, AquaDragon commented on src/board/TextPanel/Chat.tsx
> +  private entryBoxRef: React.RefObject<HTMLInputElement>;
ah ok i was wondering how to get that to work

2023-04-27 06:21 UTC, kevinddchen commented
OK, I did the following:
- check the log radio button on page load
- reenable "enter" to send message

Let me know if this looks good. You will have to approve before either of us can merge.

> The linter keeps failing due to some null-assertion error and I'm not familiar with styling textscript, so that has to be fixed.

For the record, you actually passed the linter. That `null-assertion` thing was just a warning. I don't know how to solve that issue, so we have to deal with it for the time being 😅 . The actual error was from the `prettier`, meaning your code formatting needed to be fixed. But thats super trivial stuff, like indenting and what not.

> I just thought of a continuation we could do with the game log/chat buttons in which the tab that is not open could flash or change color if there is an update while it is not shown (i.e. if you're in the Game Log and there is a new Chat message, the tab will turn red or something)

I really like this idea. We can do it later, but just open an issue for now so we don't forget.

2023-04-27 06:29 UTC, kevinddchen commented
Do you think it makes more sense to put the buttons on the bottom? Less distance between clicking "Game Log/Chat" and the input field / "Send" button?

2023-04-28 04:25 UTC, AquaDragon commented
> For the record... You can fix it automatically by running `npm run prettier:fix`.

I just saw this at the front page while trying to fix the NODE_PATH issue 😅 

> Do you think it makes more sense to put the buttons on the bottom? Less distance between clicking "Game Log/Chat" and the input field / "Send" button?

That could be done, but I'll have find a nice looking CSS for that. The original CSS for the Game Log/Chat buttons were from the chat box header and they slowly evolved to look like tabs.

2023-04-28 04:34 UTC, AquaDragon approved these changes
Looks good. I think we can push this before starting more PRs on the other issues

2023-04-28 04:57 UTC, merged